name: devkit_sdk
description: Dart client library for DevKit - Configuration Management & Feature Flags Platform
version: 1.0.0
homepage: https://usedevkit.com
repository: https://github.com/usedevkit/sdk-flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.2
